version: "3.9"
services:
  mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
        MONGO_INITDB_DATABASE: testdb
      ports:
        - "27017:27017"
      volumes:
        - mongo:/data/db
        - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongo:

networks:
  backbots:
    name: "backbots"
    driver: bridge
